package domeform;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//import workshop.Quenmatkhau;
//import workshop.DangNhapNV;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ASUS
 */
public class Logindome extends javax.swing.JFrame {

    Connection con = null;
    Statement st = null;
    ResultSet rs = null;

    /**
     * Creates new form Login
     */
    public Logindome() {
        initComponents();
        setLocationRelativeTo(null);
        RuingChu();
        try {
            ketnoi();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Logindome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Logindome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void RuingChu() {
        new Thread() {
            public void run() {
                String text = jLbten.getText() + (" ");

                while (true) {

                    text = text.substring(1, text.length()) + text.charAt(0);
//                                          text1 = text1.substring(1, text1.length());
                    try {
                        sleep(500);
                        jLbten.setText(text);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }.start();
    }

    public void ketnoi() throws ClassNotFoundException, SQLException {
        String user = "sa";
        String password = "123";
        String database = "QLXE";
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost:1433;databaseName=" + database + ";encrypt=true;trustServerCertificate=true;";
        con = DriverManager.getConnection(url, user, password);
    }

    // đăng nhập
    boolean Check() {
        if (txtUsername.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "User Không được để trống");
            return false;
        }

        if (txtPassword.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Password Không được để trống");
            return false;
        }
        return true;

    }

    public void dangnhap() throws SQLException {
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        st = con.createStatement();
        String sql = "Select * from users where username='" + username + "' and password='" + password + "'";
        rs = st.executeQuery(sql);
        if (rs.isBeforeFirst() == false) {
            JOptionPane.showMessageDialog(this, "Tài khoản với mật không đúng");
        } else {
            JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
            boolean admin = false;
            while (rs.next()) {
                admin = rs.getBoolean("admin");
            }
            if (admin) {
                new Home().setVisible(true);
                this.dispose();
                // trang muốn chuyển vô
//                            FrmAdmin fadmin = new FrmAdmin();
//                            fadmin.show();
            } else {
                //trang muốn chuyển vô nếu nó là user
//                            FrmUser fuser = new FrmUser();
//                            fuser.show();
            }
            dispose();//ẩn form login
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popMenu = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        lblQuenmk = new javax.swing.JLabel();
        lblDangki = new javax.swing.JLabel();
        btnE = new javax.swing.JButton();
        jLbten = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jMenuItem1.setText("Xem");
        popMenu.add(jMenuItem1);

        jMenuItem2.setText("Sắp xếp");
        popMenu.add(jMenuItem2);

        jMenuItem3.setText("Làm mới");
        popMenu.add(jMenuItem3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Sign in");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 100, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Username:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtUsername.setBackground(new java.awt.Color(255, 250, 252));
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 280, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, -1));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 280, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(5, 130, 130));
        jLabel5.setText("User Login");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 40));

        lblQuenmk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuenmk.setText("Quên mật khẩu?");
        lblQuenmk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblQuenmkMouseReleased(evt);
            }
        });
        jPanel1.add(lblQuenmk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, 30));

        lblDangki.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDangki.setText("Đăng ký");
        lblDangki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblDangkiMouseReleased(evt);
            }
        });
        jPanel1.add(lblDangki, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 90, 30));

        btnE.setBackground(new java.awt.Color(0, 153, 102));
        btnE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnE.setText("EXIT");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });
        jPanel1.add(btnE, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 70, 30));

        jLbten.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLbten.setForeground(new java.awt.Color(0, 102, 102));
        jLbten.setText("LH.KIÊN -NH.NINH");
        jPanel1.add(jLbten, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 340, 420));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anh-nen-cong-nghe-dep_103227227.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnEActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (Check()) {
            try {
                dangnhap();
            } catch (SQLException ex) {
                Logger.getLogger(Logindome.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        //        {
//            if(txtUsername.getText().equalsIgnoreCase("ADMIN")&&txtPassword.getText().equalsIgnoreCase("ADMIN"))
//          {
//              new Home().setVisible(true);
//              this.dispose();
//              
//          }
//          else if(txtUsername.getText().equalsIgnoreCase("admin")&&txtPassword.getText().equalsIgnoreCase("admin"))
//          {   
//              this.dispose();
//              new Home().setVisible(true);
//              this.dispose();
//          }
//          else if(txtUsername.getText().equalsIgnoreCase("") && txtPassword.getText().equalsIgnoreCase("")){
//              JOptionPane.showMessageDialog(this, "Bạn chưa nhập tên tài khoản hoặc mật khẩu !!!");
//          }
//          else{
//              JOptionPane.showMessageDialog(this,"Tên tài khoản hoặc mật khẩu mà bạn nhập không đúng !!!"+"\n"+"Mời bạn nhập lại username hoặc password !!!");
//          }
//    }   
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblDangkiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangkiMouseReleased
//      new DangNhapNV().setVisible(true);
//      this.dispose();
    }//GEN-LAST:event_lblDangkiMouseReleased

    private void lblQuenmkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenmkMouseReleased
        new Quenmatkhau().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblQuenmkMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logindome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logindome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logindome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logindome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logindome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLbten;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDangki;
    private javax.swing.JLabel lblQuenmk;
    private javax.swing.JPopupMenu popMenu;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
